### ISSUE TITLE
No servers for country found.

### ISSUE THREAD

**Issue by yadrena** [bastiandoetsch/mullvad-best-server#4]
Windows 10

 .\mullvad-best-server_20220319.170048_Windows_x86_64.exe -c de
 
 results with
{"level":"fatal","country":"de","time":"2022-07-09T00:02:17+03:00","message":"No servers for country found."}

**Comment by bastiandoetsch** [comment]
Is this reproducible for you? Asking, because I can't reproduce it myself.

**Comment by ghost** [comment]
same here
[https://postimg.cc/w39LqpKS](url)

**Comment by bastiandoetsch** [comment]
Works for me under macOS:
```
./mullvad-best-server_20220319.170048_darwin_x86_64 -c de                                                                                                                                 
de23
```
There seems to be a syscall problem with Windows 10:
```
{"level":"error","error":"socket: The requested protocol has not been configured into the system, or no implementation for it exists.","time":"2022-07-28T20:09:42-05:00","message":"Error determining the server lat
ency via ping."}
```

**Comment by bastiandoetsch** [comment]
Please be aware that the reported server is random - functionality on Windows can only ensure that the server is up, but nothing more. The `go-ping` library gives the reason `Despite the method name, this should work without the need to elevate privileges and has been tested on Windows 10. Please note that accessing packet TTL values is not supported due to limitations in the Go x/net/ipv4 and x/net/ipv6 packages.`
